<?php

return [
    [
        'name' => 'app_url',
        'title' => 'APP接入地址',
        'type' => 'string',
        'content' => [],
        'value' => 'https://smsapi.cn-north-4.myhuaweicloud.com:443',
        'rule' => 'required',
        'msg' => '',
        'tip' => '登录管理控制台，从国内短信“应用管理”或国际/港澳台短信“应用管理”页面获取。',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'key',
        'title' => '应用key',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'secret',
        'title' => '密钥secret',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sender',
        'title' => '发送者',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => 'required',
        'msg' => '',
        'tip' => '国内短信填写为短信平台为短信签名分配的通道号码',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sign',
        'title' => '签名',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'template',
        'title' => '短信模板',
        'type' => 'array',
        'content' => [],
        'value' => [
            'register' => '8ff55xxxxxxxxxxxxxxxxxxx',
            'resetpwd' => '8ff55xxxxxxxxxxxxxxxxxxx',
            'changepwd' => '8ff55xxxxxxxxxxxxxxxxxxx',
            'changemobile' => '8ff55xxxxxxxxxxxxxxxxxxx',
            'profile' => '8ff55xxxxxxxxxxxxxxxxxxx',
            'mobilelogin' => '8ff55xxxxxxxxxxxxxxxxxxx',
            'bind' => '8ff55xxxxxxxxxxxxxxxxxxx',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => '__tips__',
        'title' => '温馨提示',
        'type' => 'string',
        'content' => [],
        'value' => 'APP接入地址、应用key和secret可以通过登录管理控制台，从国内短信“应用管理”或国际/港澳台短信“应用管理”页面获取。',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
