<?php

return [
    [
        'name' => 'EBusinessID',
        'title' => '商户ID',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'AppKey',
        'title' => 'AppKey',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'ReqURL',
        'title' => 'API请求地址',
        'type' => 'string',
        'content' => [],
        'value' => 'http://api.kdniao.com/Ebusiness/EbusinessOrderHandle.aspx',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name'    => 'rewrite',
        'title'   => '伪静态',
        'type'    => 'array',
        'content' => [],
        'value'   => [
            'index/index'         => '/kdniao/getList#get',
            'index/query'         => '/kdniao',
        ],
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
];
